# Generated by Django 4.1.7 on 2023-04-08 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='----', max_length=32, verbose_name='Название')),
                ('category', models.CharField(choices=[('СПРАВКА', 'Справка'), ('ПАСПОРТ', 'Паспорт'), ('СВИД', 'Свидетельство'), ('ДИПЛОМ', 'Диплом')], default='СПРАВКА', max_length=16, verbose_name='Тип документа')),
                ('textDocument', models.TextField(blank=True, verbose_name='Содержание')),
                ('number', models.IntegerField(default=0, verbose_name='Номер')),
                ('dateCreate', models.DateTimeField(null=True, verbose_name='Внесён в базу')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(null=True, upload_to='media/images/', verbose_name='Изображение')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='documents.document', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
