# Generated by Django 4.1.7 on 2023-08-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(max_length=32, unique_for_date='dateCreate'),
        ),
    ]
