# Generated by Django 4.1.7 on 2023-09-24 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=24, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=24, verbose_name='Имя')),
                ('patronimic', models.CharField(blank=True, max_length=24, verbose_name='Отчество')),
                ('ITN', models.IntegerField(unique=True, verbose_name='ИНН')),
                ('post', models.CharField(max_length=24, verbose_name='Должность')),
                ('dependents', models.IntegerField(default=0, verbose_name='Дети')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Персонал',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Accruals_and_taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_year', models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], default='2023', max_length=4, verbose_name='Год')),
                ('payment_date', models.DateField(verbose_name='Дата выплаты')),
                ('reporting_date', models.DateField(verbose_name='Дата начисления')),
                ('accrued', models.FloatField(verbose_name='Начислено')),
                ('alimony', models.FloatField(default=0, verbose_name='Коэфф.Ал')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxes.staff', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Выплаты',
                'verbose_name_plural': 'Суммы выплат',
            },
        ),
    ]
