# Generated by Django 4.1.7 on 2023-03-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=24, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=24, verbose_name='Имя')),
                ('patronimic', models.CharField(blank=True, max_length=24, verbose_name='Отчество')),
                ('ITN', models.IntegerField(unique=True, verbose_name='ИНН')),
                ('post', models.CharField(max_length=24, verbose_name='Должность')),
                ('dependents', models.IntegerField(default=0, verbose_name='Дети')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Персонал',
            },
        ),
    ]
