# Generated by Django 4.1.7 on 2023-03-21 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accruals_and_taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_year', models.CharField(choices=[('2023', '2023'), ('2024', '2023'), ('2025', '2024'), ('2026', '2026')], default='2023', max_length=4, verbose_name='Год')),
                ('reporting_quarter', models.CharField(choices=[('ЯНВ', 'ЯНВ'), ('ФЕВР', 'ФЕВР'), ('МАРТ', 'МАРТ'), ('АПР', 'АПР'), (' МАЙ', 'МАЙ'), ('ИЮНЬ', 'ИЮНЬ'), ('ИЮЛЬ', 'ИЮЛЬ'), ('АВГ', 'АВГ'), ('СЕНТ', 'СЕНТ'), ('ОКТ', 'ОКТ'), ('НОЯБ', 'НОЯБ'), ('ДЕК', 'ДЕК')], default='ЯНВ', max_length=4, verbose_name='Квартал')),
                ('reporting_month', models.CharField(choices=[('3 мес.', '3 мес.'), ('6 мес.', '6 мес.'), ('9 мес.', '9 мес.'), ('Год', 'Год')], default='3 мес.', max_length=6, verbose_name='Месяц')),
                ('payment_date', models.DateField(verbose_name='Внесён в базу')),
                ('accrued', models.FloatField(verbose_name='Начислено')),
                ('alimony', models.FloatField(default=0, verbose_name='Алименты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxes.staff', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Зарплата',
                'verbose_name_plural': 'Суммы выплат',
            },
        ),
    ]
