# Generated by Django 4.1.7 on 2023-03-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_accruals_and_taxes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accruals_and_taxes',
            options={'verbose_name': 'Выплаты', 'verbose_name_plural': 'Суммы выплат'},
        ),
        migrations.AlterField(
            model_name='accruals_and_taxes',
            name='alimony',
            field=models.FloatField(default=0, verbose_name='Коэфф.Ал'),
        ),
        migrations.AlterField(
            model_name='accruals_and_taxes',
            name='payment_date',
            field=models.DateField(verbose_name='Дата выплаты'),
        ),
        migrations.AlterField(
            model_name='accruals_and_taxes',
            name='reporting_month',
            field=models.CharField(choices=[('ЯНВ', 'ЯНВ'), ('ФЕВР', 'ФЕВР'), ('МАРТ', 'МАРТ'), ('АПР', 'АПР'), (' МАЙ', 'МАЙ'), ('ИЮНЬ', 'ИЮНЬ'), ('ИЮЛЬ', 'ИЮЛЬ'), ('АВГ', 'АВГ'), ('СЕНТ', 'СЕНТ'), ('ОКТ', 'ОКТ'), ('НОЯБ', 'НОЯБ'), ('ДЕК', 'ДЕК')], default='ЯНВ', max_length=4, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='accruals_and_taxes',
            name='reporting_quarter',
            field=models.CharField(choices=[('3 мес.', '3 мес.'), ('6 мес.', '6 мес.'), ('9 мес.', '9 мес.'), ('Год', 'Год')], default='3 мес.', max_length=6, verbose_name='Квартал'),
        ),
    ]
